export const BP = "basePath"
export const BR = "brain"
export const CO = "content" // comes from cosmiconfig
export const CC = "config" // comes from cosmiconfig
export const CF = "configFile"
export const FI = "filepath"
export const FT = "fileTypes"
export const MC = "control"
export const NS = "namespace"
export const RT = "root"
export const GLOB = "glob"
export const TK = "telepathy"
export const ST = "stats"
export const DA = "data"
export const DR = "dryRun"
export const FC = "fileContent"
export const RP = "relativePath"

export const INIT = `init`
