export const SETTINGS = '/settings'
export const PROFILE = '/settings/profile'
export const LOGIN = '/settings/login'
export const LOGOUT = '/settings/logout'
export const LEARN = '/learn'
export const CONTRIBUTE = '/contribute'
export const CONTRIBUTE_EXAMPLE = '/contribute/an-example'
export const ASK = '/ask'
